version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: API-CEP

    ports:
      - "5432:5432"
    volumes:
        - ./data:/var/lib/postgresql/data

volumes:
  postgres_data: